WebApplication/Controllers/MaterialController.cs
// Файл: WebApplication/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebApplication.Data.Interfaces;
using WebApplication.Data.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class MaterialController : Controller
    {
        private readonly IWebAppRepository _repository;
        private readonly IAuthorizationService _authService;

        private readonly UserManager<ApplicationUser> _userManager;

        public MaterialController(IWebAppRepository repository,
                                IAuthorizationService authService,
                                UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _authService = authService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUserId = _userManager.GetUserId(User);

            var materials = await _repository.ReadWhere<Material>(m => m.AuthorId == currentUserId)
                                           .ToListAsync();
            return View(materials);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var material = await _repository.ReadSingleAsync<Material>(m => m.Id == id);

            if (material == null) return NotFound();

            var authorizationResult = await _authService.AuthorizeAsync(
                User, material, "CanManageMaterial");

            if (!authorizationResult.Succeeded)
            {

                return Forbid();
            }

            return View(material);
        }

        public async Task<IActionResult> CreateTestMaterial()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var newMaterial = new Material
            {
                Title = $"Матеріал, створений {currentUser.Email}",
                Content = "Цей матеріал створив я.",
                AuthorId = currentUser.Id
            };

            await _repository.AddAsync(newMaterial);

            return Ok($"Створено матеріал з ID: {newMaterial.Id}");
        }
    }
}

WebApplication/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication.ViewModels;
using Microsoft.Extensions.Localization;
namespace WebApplication.Controllers
{
    public class OrderController : Controller
    {
        private readonly IStringLocalizer<OrderViewModel> _localizer;

        public OrderController(IStringLocalizer<OrderViewModel> localizer)
        {
            _localizer = localizer;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(OrderViewModel model)
        {

            if (ModelState.IsValid)
            {
                return Content($"Замовлення прийнято! Товар: {model.ProductName}, Кількість: {model.Quantity}");
            }

            return View(model);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyEmail(string customerEmail)
        {

            if (customerEmail.ToLower() == "admin@example.com")
            {
                return Json($"Email {customerEmail} вже зайнятий (для тесту).");
            }

            return Json(true);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyPromoCode(string promoCode, decimal price, int quantity)
        {
            if (string.Equals(promoCode, "LNU2025", StringComparison.OrdinalIgnoreCase))
            {
                var totalAmount = price * quantity;

                if (totalAmount < 100)
                {
                    return Json(_localizer["PromoCodeAmountError", promoCode, totalAmount].Value);
                }
            }
            else
            {
                return Json(_localizer["PromoCodeInvalidError", promoCode].Value);
            }

            return Json(true);
        }

    }
}

WebApplication/Controllers/SelectLanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Controllers
{
    public class SelectLanguageController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            var cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture));

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName, 
                cookieValue,
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
@*                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Archive">Archive</a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Material" asp-action="CreateTestMaterial">Create Test Material</a>
                        </li>
                        <li class="nav-item">
                              <a class="nav-link text-dark" asp-area="" asp-controller="Material" asp-action="Index" asp-route-id="1">Check my materials</a>
                        </li>
                        <li class="nav-item">
                              <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Premium">Premium</a>
                        </li>
                        <li class="nav-item">
                              <a class="nav-link text-info" asp-area="" asp-controller="Home" asp-action="Forum">Forum</a>
                        </li>    *@
                        <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Create">Create Order</a>
                        </li>
                    </ul>
                    <partial name="_SelectLanguagePartial" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - @ViewData["ApplicationName"] - <a href="@ViewData["ApiUrl"]">API Link</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="SelectLanguage" 
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-horizontal" role="form">
        
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label>
        
        <select name="culture" 
                onchange="this.form.submit();" 
                asp-for="@requestCulture.RequestCulture.UICulture.Name" 
                asp-items="cultureItems"
                class="form-select d-inline w-auto">
        </select>
    </form>
</div>